spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/em
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:cuaderno3}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

logging:
  level:
    com.brenis.em: DEBUG
